Homepage
ntzwilly/newsweek-replica pull request #1
Opened 2021-02-02 14:00 UTC by ntzwilly

##Project 3: Using Bootstrap - Milestone 1 

Description: 

#Set up a new the repository
#Prepare the main HTML file
#Install Bootstrap in your project
#Prepare your project to work with 3 screen sizes: mobile, tablet, and desktop using the Bootstrap responsive grid classes
#Create these sections of the website for the 3 screen sizes: Header and Footer.

2021-02-02 16:17 UTC, Spayco requested changes
# Invalid 🛑 

Hello, you've made great progress, but I can't review your work unless the requirements below are met 👇 

## do NOT move to the next milestone, fix the issue below, and ask for another review.

- [x] The project should have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-03 02:34 UTC, ntzwilly commented
# Project 3: Using Bootstrap - Milestone 1

## Description:

1. Set up a new the repository
2. Prepare the main HTML file
3. Install Bootstrap in your project
4. Prepare your project to work with 3 screen sizes: mobile, tablet, and desktop using the Bootstrap
5. Responsive grid classes
6. Create these sections of the website for the 3 screen sizes

2021-02-03 03:19 UTC, jubaan requested changes

2021-02-03 03:19 UTC, jubaan commented on style.css
> +  background-color: #fff;
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on style.css
> +  color: #fff;
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on style.css
> +  display: inline;
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on style.css
> +  font-weight: bold;
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on style.css
> +  display: block;
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on style.css
> +  padding: 0;
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on style.css
> +  padding-left: 0;
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on style.css
> +  font-weight: bold;
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on style.css
> +  display: inline;
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on style.css
> +  text-decoration: underline;
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on style.css
> +}
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on style.css
> +  font-weight: bold;
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on style.css
> +  font-weight: bold;
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on style.css
> +  font-weight: bold;
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on style.css
> +  color: black;
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on style.css
> +  font-weight: bold;
- [ ] Bootstrap

2021-02-03 03:19 UTC, jubaan commented on index.html
> +              <span class = "footer-two">Announcements</span>
- [ ] Use semantic HTML for the links `<a>`

2021-02-03 03:19 UTC, jubaan commented on index.html
> +              <span class = "footer-two">România</span>
- [ ] Use semantic HTML for the links `<a>`

2021-02-03 03:19 UTC, jubaan commented on index.html
> +              <li class = "nav-item grey red-hover">CAPITOL RIOTS</li>
- [ ] Use semantic HTML for the links `<a>`

2021-02-03 03:19 UTC, jubaan commented on index.html
> +              </li>
- [ ] Should use a form with a search input

2021-02-03 03:19 UTC, jubaan commented on index.html
> +              <li class = "items red-hover">Vantage</li>
- [ ] Use semantic HTML for the links `<a>`

2021-02-03 03:19 UTC, jubaan commented on index.html
> +            <span><button id = "btn-sub">SUBSCRIBE ></button></span>
- [ ] Use semantic HTML for the links `<a>`

2021-02-03 03:19 UTC, jubaan commented on index.html
> +            </div>
- [ ] Code is duplicated, use Bootstrap classes with media query syntax to accomplish the same

2021-02-03 03:19 UTC, jubaan commented on index.html
> +              Newsweek
- [ ] Newsweek in header and footer is a link also. Use an anchor tag for both of them `<a>`

2021-02-03 13:35 UTC, ntzwilly commented
# Project 3: Using Bootstrap - Milestone 1

## Description:

1. Set up a new the repository
2. Prepare the main HTML file
3. Install Bootstrap in your project
4. Prepare your project to work with 3 screen sizes: mobile, tablet, and desktop using the Bootstrap
5. Responsive grid classes
6. Create these sections of the website for the 3 screen sizes

## Corrected all code review feedbacks

2021-02-03 16:46 UTC, Spayco approved these changes
# Project Approved ✔️ 

Sorry for the confusion, milestone 1 and 2 should always be approved, but seems that the previous TSE marked it by mistake to "changes requested" 
you can go ahead and move to the next milestone while focusing on what the previous TSE said.

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-04 10:24 UTC, ntzwilly commented
# Project 3: Using Bootstrap - Milestone 1

In the second milestone, I create the 3 columns main section of the website for the 3 screen sizes.

## Column 1

Featured stories
Sponsored insights / Rankings

##Column 2

Top story
My turn
Culture & travel
More stories
Latest news

##Column 3

The debate Opinion Sponsored insights / Rankings Free signup

2021-02-04 19:36 UTC, Spayco approved these changes
# Project Approved ✔️ 

Milestone approved, however, there are things that you need to change, you can either make the changes now, or you keep them to the last milestone. but keep in mind **all these changes unless marked optional will be MANDATORY in the third milestone**.

- [x] the 'Sponsored Insight' should be blue.
- [ ] you have a lot of CSS properties that can be turned into Bootstrap classes, it's recommended to fix those from now as it's mandatory for them to be fixed in order for the project to be approved in Milestone 3.

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-04 22:00 UTC, ntzwilly commented
# Newsweek-replica

I was required to complete the milestones below to learn bootstrap. This project consists of replicating the Newsweek website putting emphasis on how it behaves differently depending on the size of the screen where the website is rendered.

## Below are the major concepts I learned:

- Ability to create UIs adaptable to different screen sizes using media queries
- Use a CSS framework like Bootstrap
- Apply front-end best practices
- Create UIs adjusted to given designs
- Understand the usefulness of transitions and animations

## Project 3: Using Bootstrap - Milestone 1

- Set up a new the repository
- Prepare the main HTML file
- Install Bootstrap in your project
- Prepare your project to work with 3 screen sizes: mobile, tablet, and desktop using the Bootstrap responsive grid classes
- Create these sections of the website for the 3 screen sizes

## Milestone 2 

In the second milestone, you will create the 3 columns main section of the website for the 3 screen sizes.

## Column 1

- Featured stories
- Sponsored insights / Rankings

## Column 2

- Top story
- My turn
- Culture & travel
- More stories
- Latest news

## Column 3

- The debate
- Opinion
- Sponsored insights / Rankings
- Free signup

## Milestone 3 - complete mobile version

The third and last milestone of the project is to complete the last sections of the website and prepare it for my portfolio.

2021-02-05 10:08 UTC, PhillipUg requested changes
Hey team, 👋

You have done an amazing job implementing the requirements for this project.

However, there are still some changes 👇 you need to implement to approve this request 🔍

### Changes Required ♻️ 

- [x] All the images of the `More stories`, `Latest News` and the `In the Magazine` sections and all the other images that follow below should have links.
- [x] The navigation items at the bottom in the footer should all have links.
- [x] All the titles in the different sections should use hx tags (h1 - h6). 
- [x] Newsletter section at the bottom should have an input with type email

#### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime** or
 <a href="mailto:phillipmusiime@gmail.com"> <img alt="gmail" src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social" target="_blank"></a> &nbsp; &nbsp; [![Twitter Follow](https://img.shields.io/twitter/follow/Phillip_Ug?style=social)](https://twitter.com/intent/follow?screen_name=Phillip_Ug) &nbsp; &nbsp; [![GitHub followers](https://img.shields.io/github/followers/phillipug?label=Follow&style=social)](https://github.com/PhillipUg)

2021-02-05 12:41 UTC, ntzwilly commented
## Thank you for your feedback. I have made the required changes:

- All the images of the More stories, Latest News and the In the Magazine sections and all the other images that follow below should have links.
- The navigation items at the bottom in the footer should all have links.
- All the titles in the different sections should use hx tags (h1 - h6).
- Newsletter section at the bottom should have an input with type email

2021-02-05 16:30 UTC, Spayco approved these changes
# Project Approved ✔️ 

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-05 17:06 UTC, merged